// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Module {
    "id": string;
    "name": string;
    "enabled": boolean;

    /**
     * YAML, a mapping
     */
    "body": string;

    /**
     * the ID of the profile it is laid over alone; empty, over every one
     */
    "profile"?: string;

    /**
     * a service sent through a policy: the body is made from it, again
     * for each profile (runtimecfg), so its group's name never clashes
     */
    "route"?: Route | null;

    /**
     * a node or group served on a SOCKS5 port of its own
     */
    "port"?: Port | null;

    /**
     * for YAML taken from a kind's form, the kind it was: going back to the
     * form restores it, dropping the YAML
     */
    "was"?: Module | null;
}

/**
 * Port is a module that serves one node or group on a SOCKS5 port of its
 * own: what connects there leaves by it, whatever the rules and the mode
 * say. The node is named per profile, since a name belongs to one
 * subscription; a profile with none picked gets no port.
 */
export interface Port {
    "port": number;

    /**
     * a Listens address; "" is the first
     */
    "listen"?: string;

    /**
     * node or group, by profile ID
     */
    "target"?: { [_ in string]?: string } | null;
    "udp": boolean;
    "user"?: string;
    "pass"?: string;
}

/**
 * Route is a module that sends one service through a policy of its own,
 * as Surge's service groups do. Like every module it is laid over every
 * profile, and its group takes the nodes of the one in use: all of them, a
 * region's, or picked ones. Picked nodes are named per profile, since a
 * name belongs to one subscription, and keywords hold for all. A group
 * with no node refuses its connections rather than letting them out
 * direct: picking says these nodes and no others.
 */
export interface Route {
    /**
     * a Services name
     */
    "service": string;

    /**
     * select, url-test or DIRECT
     */
    "policy": string;

    /**
     * a Regions key
     */
    "region"?: string;

    /**
     * only Nodes and Keywords
     */
    "pick"?: boolean;

    /**
     * by profile ID: names, matched whole
     */
    "nodes"?: { [_ in string]?: string[] | null } | null;

    /**
     * matched anywhere in a name, any case
     */
    "keywords"?: string[] | null;

    /**
     * front proxy, by profile ID
     */
    "upstream"?: { [_ in string]?: string } | null;
}

/**
 * Service is what a route matches: the rules that pick out its traffic.
 */
export interface Service {
    /**
     * also its group's
     */
    "name": string;
    "hint": string;

    /**
     * TYPE,payload, with options after the policy
     */
    "rules": string[] | null;

    /**
     * the one it starts with
     */
    "region"?: string;
}

/**
 * Template is a module offered ready-made, for the cases most people add
 * one for. Hint says in a line what it does and when to want it. A template
 * opens in the editor, to be read and changed before it's added.
 */
export interface Template {
    "name": string;
    "hint": string;
    "body": string;
}
