// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the app and its windows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppIcon is an app's icon (a bundle or executable path; "" for a LAN
 * client) as a PNG data URL, for the page to show.
 */
export function AppIcon(path: string): $CancellablePromise<string> {
    return $Call.ByID(3141288265, path);
}

/**
 * ChooseApp asks for an app or an executable; a cancelled dialog is the
 * zero App.
 */
export function ChooseApp(): $CancellablePromise<$models.App> {
    return $Call.ByID(2737570799);
}

export function ClearEvents(): $CancellablePromise<void> {
    return $Call.ByID(1703361915);
}

/**
 * Connectivity measures router, DNS, internet and proxy latency.
 */
export function Connectivity(): $CancellablePromise<backend$0.Connectivity> {
    return $Call.ByID(1676079710);
}

/**
 * ConnectivityItem measures one of "router", "dns", "internet", "proxy";
 * only that item's fields are set.
 */
export function ConnectivityItem(key: string): $CancellablePromise<backend$0.Connectivity> {
    return $Call.ByID(1432809917, key);
}

export function CopyText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1618543495, text);
}

/**
 * DNSEgress is the resolver in use and the address its queries leave from.
 */
export function DNSEgress(): $CancellablePromise<backend$0.DNSEgress> {
    return $Call.ByID(3851272135);
}

/**
 * DirectEgress is the direct route's interface and public address.
 */
export function DirectEgress(): $CancellablePromise<backend$0.Egress> {
    return $Call.ByID(3018527287);
}

/**
 * DisableServiceMode runs the core as the user again; uninstall removes the helper.
 */
export function DisableServiceMode(uninstall: boolean): $CancellablePromise<void> {
    return $Call.ByID(1662789921, uninstall);
}

/**
 * EnableServiceMode installs the privileged helper (asking for a password).
 */
export function EnableServiceMode(): $CancellablePromise<void> {
    return $Call.ByID(966595062);
}

/**
 * Events is the recent events, oldest first.
 */
export function Events(): $CancellablePromise<backend$0.Event[] | null> {
    return $Call.ByID(1767932624);
}

/**
 * FitPanel sizes the tray panel to its page's height (CSS pixels), gliding
 * over ms when it is shown.
 */
export function FitPanel(height: number, ms: number): $CancellablePromise<void> {
    return $Call.ByID(3889214102, height, ms);
}

/**
 * HelperStatus is service mode's state, for Settings.
 */
export function HelperStatus(): $CancellablePromise<backend$0.HelperStatus> {
    return $Call.ByID(3732919099);
}

export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(3127844849);
}

/**
 * LANProxyCommand is the same for this Mac's LAN address, for another
 * machine to use (Allow LAN must be on); "" when the Mac has none.
 */
export function LANProxyCommand(): $CancellablePromise<string> {
    return $Call.ByID(3811387141);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1821707918, url);
}

/**
 * ProxyCommand is the shell export line for the mixed port.
 */
export function ProxyCommand(): $CancellablePromise<string> {
    return $Call.ByID(4092743996);
}

/**
 * ProxyEgress is where proxied traffic leaves, and the chain it took.
 */
export function ProxyEgress(): $CancellablePromise<backend$0.ProxyEgress> {
    return $Call.ByID(117796648);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(550236858);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(3972975136);
}

export function RevealData(): $CancellablePromise<void> {
    return $Call.ByID(1194505660);
}

/**
 * RevealData opens the app's data folder in Finder.
 * RunningApps is the apps running now, for a process rule to name.
 */
export function RunningApps(): $CancellablePromise<$models.App[] | null> {
    return $Call.ByID(72655528);
}

export function SetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3544230680, mode);
}

export function SetSystemProxy(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3320185786, on);
}

export function SetTun(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(700666950, on);
}

/**
 * ShowMain opens the main window, on view if one is given.
 */
export function ShowMain(view: string): $CancellablePromise<void> {
    return $Call.ByID(821886749, view);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1280175915);
}

export function State(): $CancellablePromise<backend$0.State> {
    return $Call.ByID(1061184298);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1976075929);
}
