// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Group is a proxy group with its members, in the profile's order.
 */
export interface Group {
    "name": string;
    "type": string;
    "now": string;
    "hidden": boolean;
    "icon": string;
    "testUrl": string;
    "members": Member[] | null;
}

export interface Member {
    "name": string;
    "type": string;
    "udp": boolean;

    /**
     * last test, ms; 0 untested, -1 failed
     */
    "delay": number;

    /**
     * a group itself
     */
    "group": boolean;
}

/**
 * Patch is a partial update: the keys of p (as settings.json names them)
 * that are present are changed.
 */
export interface Patch {
    "mixedPort"?: number | null;
    "allowLan"?: boolean | null;
    "ipv6"?: boolean | null;
    "logLevel"?: string | null;
    "tunStack"?: string | null;
    "icmpForwarding"?: boolean | null;
    "bypass"?: string[] | null;
    "autoStart"?: boolean | null;
    "launchAtLogin"?: boolean | null;
    "theme"?: string | null;
    "lang"?: string | null;
    "dock"?: string | null;
    "testUrl"?: string | null;
    "traySpeed"?: boolean | null;
    "findProcess"?: boolean | null;
    "notify"?: boolean | null;
}

/**
 * Provider is a proxy provider with its nodes, as the profile lists them.
 */
export interface Provider {
    "name": string;

    /**
     * HTTP | File | Inline
     */
    "vehicleType": string;
    "testUrl": string;
    "updatedAt": string;
    "upload": number;
    "download": number;
    "total": number;
    "expire": number;
    "members": Member[] | null;
}
