// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService is the profiles.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modules$0 from "../modules/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiles$0 from "../profiles/models.js";

/**
 * Duplicate copies a profile as a local one the user can edit; name is
 * the copy's.
 */
export function Duplicate(id: string, name: string): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(1526146004, id, name);
}

export function Edit(id: string, name: string, interval: number): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(548408207, id, name, interval);
}

/**
 * ImportFile asks for a YAML file and imports it; an empty profile when the
 * user cancelled.
 */
export function ImportFile(): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(2189063916);
}

export function ImportURL(url: string, name: string, interval: number): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(2903618323, url, name, interval);
}

export function List(): $CancellablePromise<profiles$0.Profile[] | null> {
    return $Call.ByID(4210285211);
}

/**
 * ModuleKeys is the top-level keys a module's body sets, for its summary;
 * an error says why the body isn't a module.
 */
export function ModuleKeys(body: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(125334863, body);
}

/**
 * ModuleTemplates is the ready-made modules.
 */
export function ModuleTemplates(): $CancellablePromise<modules$0.Template[] | null> {
    return $Call.ByID(1166326602);
}

/**
 * Modules is the user's modules, merged over every profile in order.
 */
export function Modules(): $CancellablePromise<modules$0.Module[] | null> {
    return $Call.ByID(3717581476);
}

/**
 * Edit opens a profile's file in the default editor.
 */
export function OpenInEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(3771928797, id);
}

export function Remove(id: string): $CancellablePromise<void> {
    return $Call.ByID(4085670399, id);
}

/**
 * Reveal shows a profile's file in Finder.
 */
export function Reveal(id: string): $CancellablePromise<void> {
    return $Call.ByID(1550090246, id);
}

/**
 * RouteBody is the YAML a route makes, to open as a module of its own.
 */
export function RouteBody(r: modules$0.Route): $CancellablePromise<string> {
    return $Call.ByID(310144396, r);
}

/**
 * RouteNodes is the running profile's nodes, for a route to pick from.
 */
export function RouteNodes(): $CancellablePromise<backend$0.Node[] | null> {
    return $Call.ByID(594942573);
}

/**
 * RouteRegions is the regions a route's group can take nodes by, each with
 * how many of the running profile's nodes it takes.
 */
export function RouteRegions(): $CancellablePromise<backend$0.RegionNodes[] | null> {
    return $Call.ByID(2458093525);
}

/**
 * RouteServices is the services a module can send through a policy.
 */
export function RouteServices(): $CancellablePromise<modules$0.Service[] | null> {
    return $Call.ByID(3699336864);
}

/**
 * SetModules replaces them; a configuration the core refuses keeps the
 * previous ones.
 */
export function SetModules(ms: modules$0.Module[] | null): $CancellablePromise<void> {
    return $Call.ByID(1311253774, ms);
}

/**
 * TakeImportRequests transfers pending links to the main window's import queue.
 */
export function TakeImportRequests(): $CancellablePromise<profiles$0.ImportRequest[] | null> {
    return $Call.ByID(3937850699);
}

export function Update(id: string): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(52250130, id);
}

/**
 * UpdateAll refreshes every subscription; the names of those that failed.
 */
export function UpdateAll(): $CancellablePromise<string[] | null> {
    return $Call.ByID(647465737);
}

export function Use(id: string): $CancellablePromise<void> {
    return $Call.ByID(1651199074, id);
}
