// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService is the profiles.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiles$0 from "../profiles/models.js";

export function Edit(id: string, name: string, interval: number): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(548408207, id, name, interval);
}

/**
 * ImportFile asks for a YAML file and imports it; an empty profile when the
 * user cancelled.
 */
export function ImportFile(): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(2189063916);
}

export function ImportURL(url: string, name: string, interval: number): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(2903618323, url, name, interval);
}

export function List(): $CancellablePromise<profiles$0.Profile[] | null> {
    return $Call.ByID(4210285211);
}

/**
 * Edit opens a profile's file in the default editor.
 */
export function OpenInEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(3771928797, id);
}

export function Remove(id: string): $CancellablePromise<void> {
    return $Call.ByID(4085670399, id);
}

/**
 * Reveal shows a profile's file in Finder.
 */
export function Reveal(id: string): $CancellablePromise<void> {
    return $Call.ByID(1550090246, id);
}

/**
 * TakeImportRequests transfers pending links to the main window's import queue.
 */
export function TakeImportRequests(): $CancellablePromise<profiles$0.ImportRequest[] | null> {
    return $Call.ByID(3937850699);
}

export function Update(id: string): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(52250130, id);
}

/**
 * UpdateAll refreshes every subscription; the names of those that failed.
 */
export function UpdateAll(): $CancellablePromise<string[] | null> {
    return $Call.ByID(647465737);
}

export function Use(id: string): $CancellablePromise<void> {
    return $Call.ByID(1651199074, id);
}
