// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService is the core's proxies, groups, connections and rules.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mihomoapi$0 from "../mihomoapi/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseAllConnections(): $CancellablePromise<void> {
    return $Call.ByID(2368338258);
}

export function CloseConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(3260682086, id);
}

export function Connections(): $CancellablePromise<mihomoapi$0.Connections> {
    return $Call.ByID(1837008931);
}

/**
 * Delay tests one proxy: ms, or -1 when it failed.
 */
export function Delay(name: string, testURL: string): $CancellablePromise<number> {
    return $Call.ByID(3819145257, name, testURL);
}

export function FlushDNS(): $CancellablePromise<void> {
    return $Call.ByID(305162487);
}

/**
 * GroupDelay tests every member of a group: name → ms, -1 failed.
 */
export function GroupDelay(group: string, testURL: string): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(3806647996, group, testURL);
}

/**
 * Groups is every proxy group, GLOBAL last.
 */
export function Groups(): $CancellablePromise<$models.Group[] | null> {
    return $Call.ByID(2943322750);
}

export function Rules(): $CancellablePromise<mihomoapi$0.Rule[] | null> {
    return $Call.ByID(647292905);
}

export function Select(group: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(141765054, group, name);
}

/**
 * TopClients is the n apps moving the most traffic, their speeds measured
 * since the last call. After a pause (the panel was hidden) it starts over,
 * and the first call has no speeds yet.
 */
export function TopClients(n: number): $CancellablePromise<backend$0.ClientRate[] | null> {
    return $Call.ByID(2078237291, n);
}

export function UpdateGeo(): $CancellablePromise<void> {
    return $Call.ByID(1571070136);
}
