// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService is the core's proxies, groups, connections and rules.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mihomoapi$0 from "../mihomoapi/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseAllConnections(): $CancellablePromise<void> {
    return $Call.ByID(2368338258);
}

export function CloseConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(3260682086, id);
}

export function Connections(): $CancellablePromise<mihomoapi$0.Connections> {
    return $Call.ByID(1837008931);
}

export function FlushDNS(): $CancellablePromise<void> {
    return $Call.ByID(305162487);
}

/**
 * Groups is every proxy group, GLOBAL last.
 */
export function Groups(): $CancellablePromise<$models.Group[] | null> {
    return $Call.ByID(2943322750);
}

/**
 * Providers is the profile's proxy providers, by name; the ones the core
 * makes for groups' own proxies are left out.
 */
export function Providers(): $CancellablePromise<$models.Provider[] | null> {
    return $Call.ByID(1937542960);
}

export function Rules(): $CancellablePromise<mihomoapi$0.Rule[] | null> {
    return $Call.ByID(647292905);
}

export function Select(group: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(141765054, group, name);
}

/**
 * TestLatency shares scheduling, progress and results across all surfaces.
 */
export function TestLatency(kind: string, name: string): $CancellablePromise<backend$0.LatencyResult> {
    return $Call.ByID(2402573828, kind, name);
}

/**
 * TopClients is the n apps moving the most traffic, their speeds measured
 * since the last call. After a pause (the panel was hidden) it starts over,
 * and the first call has no speeds yet.
 */
export function TopClients(n: number): $CancellablePromise<backend$0.ClientRate[] | null> {
    return $Call.ByID(2078237291, n);
}

export function UpdateGeo(): $CancellablePromise<void> {
    return $Call.ByID(1571070136);
}

/**
 * UpdateProvider fetches a proxy provider again.
 */
export function UpdateProvider(name: string): $CancellablePromise<void> {
    return $Call.ByID(2461202334, name);
}
