// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the app's settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1268765203);
}

export function Patch(p: $models.Patch): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(3772147429, p);
}

export function RequestWiFiPermission(): $CancellablePromise<void> {
    return $Call.ByID(2890113444);
}

/**
 * ResumeNetworkAuto drops the changes made by hand and applies the rule again.
 */
export function ResumeNetworkAuto(): $CancellablePromise<void> {
    return $Call.ByID(871465971);
}

export function SavedWiFiNetworks(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1851823466);
}

/**
 * SetNetworkAuto turns the network rules on or off.
 */
export function SetNetworkAuto(on: boolean): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(3109919596, on);
}

/**
 * SetNetworkRules replaces the network rules; the one in effect is applied.
 */
export function SetNetworkRules(rules: settings$0.NetworkRule[] | null): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2011321974, rules);
}
