// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the app and its windows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "../usage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppIcon is an app's icon (a bundle or executable path; "" for a LAN
 * client) as a PNG data URL, for the page to show.
 */
export function AppIcon(path: string): $CancellablePromise<string> {
    return $Call.ByID(3639351648, path);
}

/**
 * ChooseApp asks for an app or an executable; a cancelled dialog is the
 * zero App.
 */
export function ChooseApp(): $CancellablePromise<$models.App> {
    return $Call.ByID(3065597634);
}

export function ClearEvents(): $CancellablePromise<void> {
    return $Call.ByID(4244298330);
}

/**
 * ClearUsage forgets the traffic statistics.
 */
export function ClearUsage(): $CancellablePromise<void> {
    return $Call.ByID(949415422);
}

/**
 * Connectivity measures router, DNS, internet and proxy latency.
 */
export function Connectivity(): $CancellablePromise<backend$0.Connectivity> {
    return $Call.ByID(1372399677);
}

/**
 * ConnectivityHistory is each item's recent measures, oldest first.
 */
export function ConnectivityHistory(): $CancellablePromise<{ [_ in string]?: backend$0.LatencySample[] | null } | null> {
    return $Call.ByID(446081895);
}

/**
 * ConnectivityItem measures one of "router", "dns", "internet", "proxy";
 * only that item's fields are set.
 */
export function ConnectivityItem(key: string): $CancellablePromise<backend$0.Connectivity> {
    return $Call.ByID(3982267582, key);
}

export function CopyText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1033800820, text);
}

/**
 * DNSEgress is the resolver in use and the address its queries leave from.
 */
export function DNSEgress(): $CancellablePromise<backend$0.DNSEgress> {
    return $Call.ByID(2787700938);
}

/**
 * DirectEgress is the direct route's interface and public address.
 */
export function DirectEgress(): $CancellablePromise<backend$0.Egress> {
    return $Call.ByID(804986320);
}

/**
 * DisableServiceMode runs the core as the user again; uninstall removes the helper.
 */
export function DisableServiceMode(uninstall: boolean): $CancellablePromise<void> {
    return $Call.ByID(4159813370, uninstall);
}

/**
 * EnableServiceMode installs the privileged helper (asking for a password).
 */
export function EnableServiceMode(): $CancellablePromise<void> {
    return $Call.ByID(1417553343);
}

/**
 * Events is the recent events, oldest first.
 */
export function Events(): $CancellablePromise<backend$0.Event[] | null> {
    return $Call.ByID(1539578075);
}

/**
 * FitPanel sizes the tray panel to its page's height (CSS pixels), gliding
 * over ms when it is shown.
 */
export function FitPanel(height: number, ms: number): $CancellablePromise<void> {
    return $Call.ByID(3383759525, height, ms);
}

/**
 * HelperStatus is service mode's state, for Settings.
 */
export function HelperStatus(): $CancellablePromise<backend$0.HelperStatus> {
    return $Call.ByID(2939740836);
}

export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(4090031836);
}

/**
 * LANProxyCommand is the same for this Mac's LAN address, for another
 * machine to use (Allow LAN must be on); "" when the Mac has none.
 */
export function LANProxyCommand(): $CancellablePromise<string> {
    return $Call.ByID(3597282564);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3683581295, url);
}

/**
 * ProxyCommand is the shell export line for the mixed port.
 */
export function ProxyCommand(): $CancellablePromise<string> {
    return $Call.ByID(763102219);
}

/**
 * ProxyEgress is where proxied traffic leaves, and the chain it took.
 */
export function ProxyEgress(): $CancellablePromise<backend$0.ProxyEgress> {
    return $Call.ByID(2318133129);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2337421909);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(3635233825);
}

export function RevealData(): $CancellablePromise<void> {
    return $Call.ByID(3167104875);
}

/**
 * RevealData opens the app's data folder in Finder.
 * RunningApps is the apps running now, for a process rule to name.
 */
export function RunningApps(): $CancellablePromise<$models.App[] | null> {
    return $Call.ByID(2996144997);
}

export function SetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(1996405101, mode);
}

export function SetSystemProxy(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1747217553, on);
}

export function SetTun(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(921094421, on);
}

/**
 * ShowMain opens the main window, on view if one is given.
 */
export function ShowMain(view: string): $CancellablePromise<void> {
    return $Call.ByID(4204075058, view);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3800309646);
}

export function State(): $CancellablePromise<backend$0.State> {
    return $Call.ByID(3750270979);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3504516182);
}

/**
 * Usage is the traffic statistics of the days from..to ("2006-01-02",
 * inclusive); a single day comes in hours, and hour (0–23, else -1)
 * narrows it to one.
 */
export function Usage($from: string, to: string, hour: number): $CancellablePromise<usage$0.Report> {
    return $Call.ByID(3133726265, $from, to, hour);
}
