// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService is the core's proxies, groups, connections and rules.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mihomoapi$0 from "../mihomoapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as userrules$0 from "../userrules/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddUserRule puts a rule first.
 */
export function AddUserRule(r: userrules$0.Rule): $CancellablePromise<void> {
    return $Call.ByID(379640977, r);
}

export function CloseAllConnections(): $CancellablePromise<void> {
    return $Call.ByID(2843252139);
}

export function CloseConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(841493547, id);
}

export function Connections(): $CancellablePromise<mihomoapi$0.Connections> {
    return $Call.ByID(3700475478);
}

export function FlushDNS(): $CancellablePromise<void> {
    return $Call.ByID(2048144876);
}

/**
 * GeoInfo is when the GEO databases last changed, and whether an update runs.
 */
export function GeoInfo(): $CancellablePromise<backend$0.GeoInfo> {
    return $Call.ByID(71545170);
}

/**
 * Groups is every proxy group, GLOBAL last.
 */
export function Groups(): $CancellablePromise<$models.Group[] | null> {
    return $Call.ByID(341875237);
}

/**
 * LookupHost tells how the core resolves and routes host (a name, an
 * address, host:port or a URL).
 */
export function LookupHost(host: string): $CancellablePromise<backend$0.Lookup> {
    return $Call.ByID(3645543165, host);
}

/**
 * Providers is the profile's proxy providers, by name; the ones the core
 * makes for groups' own proxies are left out.
 */
export function Providers(): $CancellablePromise<$models.Provider[] | null> {
    return $Call.ByID(3870946869);
}

/**
 * RuleProviders is the profile's rule providers, by name.
 */
export function RuleProviders(): $CancellablePromise<mihomoapi$0.RuleProvider[] | null> {
    return $Call.ByID(2223820107);
}

/**
 * RuleTypes is the rule types a user rule can have.
 */
export function RuleTypes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(904787968);
}

export function Rules(): $CancellablePromise<mihomoapi$0.Rule[] | null> {
    return $Call.ByID(1909907368);
}

/**
 * Select picks a group's member; the old one's connections are closed so
 * the switch shows at once.
 */
export function Select(group: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3950691493, group, name);
}

/**
 * SetUserRules replaces them; the core takes them at once.
 */
export function SetUserRules(rs: userrules$0.Rule[] | null): $CancellablePromise<void> {
    return $Call.ByID(1676976719, rs);
}

/**
 * TestLatency shares scheduling, progress and results across all surfaces.
 */
export function TestLatency(kind: string, name: string): $CancellablePromise<backend$0.LatencyResult> {
    return $Call.ByID(3822694561, kind, name);
}

/**
 * TopClients is the n apps moving the most traffic, their speeds measured
 * since the last call. After a pause (the panel was hidden) it starts over,
 * and the first call has no speeds yet.
 */
export function TopClients(n: number): $CancellablePromise<backend$0.ClientRate[] | null> {
    return $Call.ByID(2635402048, n);
}

/**
 * UpdateGeo waits for the core to download its GEO databases; Updating in
 * the result means one was already under way.
 */
export function UpdateGeo(): $CancellablePromise<backend$0.GeoInfo> {
    return $Call.ByID(4045670937);
}

/**
 * UpdateProvider fetches a proxy provider again.
 */
export function UpdateProvider(name: string): $CancellablePromise<void> {
    return $Call.ByID(3963973001, name);
}

/**
 * UpdateRuleProvider fetches a rule provider again; the core keeps the
 * rules it had when the fetch fails.
 */
export function UpdateRuleProvider(name: string): $CancellablePromise<void> {
    return $Call.ByID(3944878463, name);
}

/**
 * UserRules is the rules added in the app, ahead of the profile's.
 */
export function UserRules(): $CancellablePromise<userrules$0.Rule[] | null> {
    return $Call.ByID(3940402349);
}
