// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the app's settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1183445836);
}

/**
 * Hotkeys is every action and its shortcut.
 */
export function Hotkeys(): $CancellablePromise<$models.Hotkey[] | null> {
    return $Call.ByID(3419540779);
}

export function Patch(p: $models.Patch): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(792558414, p);
}

/**
 * RecordHotkey lifts every shortcut while the page records one, so that
 * pressing a set one is recorded rather than run; false puts them back.
 */
export function RecordHotkey(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1269547523, on);
}

export function RequestWiFiPermission(): $CancellablePromise<void> {
    return $Call.ByID(3126239291);
}

/**
 * ResumeNetworkAuto drops the changes made by hand and applies the rule again.
 */
export function ResumeNetworkAuto(): $CancellablePromise<void> {
    return $Call.ByID(2005867984);
}

export function SavedWiFiNetworks(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2102391821);
}

/**
 * SetHotkey gives an action a shortcut ("" clears it). One refused (taken
 * by macOS or another action, or not a usable combination) leaves the
 * settings as they were; the error is a hotkeys.Problem.
 */
export function SetHotkey(action: string, keys: string): $CancellablePromise<$models.Hotkey[] | null> {
    return $Call.ByID(3474565066, action, keys);
}

/**
 * SetNetworkAuto turns the network rules on or off.
 */
export function SetNetworkAuto(on: boolean): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1539211897, on);
}

/**
 * SetNetworkRules replaces the network rules; the one in effect is applied.
 */
export function SetNetworkRules(rules: settings$0.NetworkRule[] | null): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1901370345, rules);
}

/**
 * UseRecommendedHotkeys gives every action without a shortcut the
 * recommended one; those already set are kept, and one macOS, another
 * action or another app holds is skipped.
 */
export function UseRecommendedHotkeys(): $CancellablePromise<$models.Recommended> {
    return $Call.ByID(3411286057);
}
