// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClientRate is one app's traffic now, as Surge's "Top Clients" lists it:
 * its name, the path its icon comes from, and its speed in bytes a second.
 */
export interface ClientRate {
    "name": string;

    /**
     * the app bundle, or the executable; "" for a LAN client
     */
    "path": string;
    "up": number;
    "down": number;
}

/**
 * Connectivity is the four latencies Surge's overview shows (docs/design.md
 * §10.4): the router, DNS, the internet directly, and through the proxy.
 * Each is in ms; 0 means not measured, -1 failed.
 */
export interface Connectivity {
    "router": number;
    "dns": number;
    "internet": number;
    "proxy": number;
    "gateway": string;

    /**
     * the policy the mode and rules sent the proxy test to
     */
    "via": string;

    /**
     * from the node out to Via
     */
    "chain": string[] | null;

    /**
     * "mihomo", or "system" when the profile has no dns section
     */
    "dnsVia": string;

    /**
     * the core's enhanced-mode: fake-ip | redir-host
     */
    "dnsMode": string;
}

/**
 * DNSEgress is where name lookups leave: the resolver that answers them
 * and the address authoritative servers see the queries come from, which
 * is the resolver's (or the proxy's), not this Mac's.
 */
export interface DNSEgress {
    /**
     * "mihomo", or "system" when the profile has no dns section
     */
    "via": string;

    /**
     * fake-ip | redir-host; "" for the system resolver
     */
    "mode": string;

    /**
     * the profile's nameservers, as written
     */
    "servers": string[] | null;

    /**
     * the egress address; "" when unknown
     */
    "ip": string;

    /**
     * the country of IP
     */
    "loc": string;

    /**
     * the client subnet passed upstream, if any
     */
    "ecs": string;
}

/**
 * Egress is where direct traffic leaves this Mac: the physical interface
 * and the public address sites see. Upstream of this Mac (a router running
 * a proxy, say) traffic may still be split by destination, so it is asked
 * of two: a mainland site, which sees the broadband line, and Cloudflare,
 * which sees where overseas traffic comes out. They differ when something
 * upstream proxies.
 */
export interface Egress {
    /**
     * e.g. en0
     */
    "interface": string;

    /**
     * its network service, e.g. Wi-Fi
     */
    "service": string;

    /**
     * as a mainland site sees it; "" when unknown
     */
    "domesticIp": string;

    /**
     * the country of DomesticIP
     */
    "domesticLoc": string;

    /**
     * as Cloudflare sees it; "" when unknown
     */
    "ip": string;

    /**
     * the country of IP
     */
    "loc": string;
}

/**
 * HelperStatus is what Settings shows of service mode.
 */
export interface HelperStatus {
    "installed": boolean;

    /**
     * runs this version of the app
     */
    "current": boolean;

    /**
     * settings.ServiceMode
     */
    "enabled": boolean;

    /**
     * the running core is the helper's
     */
    "active": boolean;
}

/**
 * LatencyEvent describes one test operation. Pending contains display names,
 * including group aliases; Delays contains only the newly completed results.
 */
export interface LatencyEvent {
    "key": string;
    "running": boolean;
    "pending": string[] | null;
    "delays": { [_ in string]?: number } | null;
    "total": number;
    "completed": number;
    "failed": number;
}

export interface LatencyResult {
    "total": number;
    "failed": number;
}

/**
 * ProxyEgress is where proxied traffic leaves: the address Cloudflare sees
 * a request through the core come from, and the chain it took.
 */
export interface ProxyEgress {
    "ip": string;
    "loc": string;

    /**
     * from the node out to the policy
     */
    "chain": string[] | null;
}

/**
 * State is what the GUI shows of the app at a glance.
 */
export interface State {
    /**
     * coremgr.Status
     */
    "core": string;
    "coreError"?: string;
    "coreVersion": string;
    "appVersion": string;
    "mode": string;
    "systemProxy": boolean;
    "tun": boolean;
    "tunStack": string;
    "serviceMode": boolean;
    "mixedPort": number;
    "profile": string;
    "profileName": string;

    /**
     * what is being done, e.g. "restarting"
     */
    "busy"?: string;
}
