// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Connectivity is the four latencies Surge's overview shows (docs/design.md
 * §10.4): the router, DNS, the internet directly, and through the proxy.
 * Each is in ms; 0 means not measured, -1 failed.
 */
export interface Connectivity {
    "router": number;
    "dns": number;
    "internet": number;
    "proxy": number;
    "gateway": string;

    /**
     * the group the proxy latency went through
     */
    "via": string;

    /**
     * "mihomo", or "system" when the profile has no dns section
     */
    "dnsVia": string;
}

/**
 * HelperStatus is what Settings shows of service mode.
 */
export interface HelperStatus {
    "installed": boolean;

    /**
     * runs this version of the app
     */
    "current": boolean;

    /**
     * settings.ServiceMode
     */
    "enabled": boolean;

    /**
     * the running core is the helper's
     */
    "active": boolean;
}

/**
 * State is what the GUI shows of the app at a glance.
 */
export interface State {
    /**
     * coremgr.Status
     */
    "core": string;
    "coreError"?: string;
    "coreVersion": string;
    "appVersion": string;
    "mode": string;
    "systemProxy": boolean;
    "tun": boolean;
    "tunStack": string;
    "serviceMode": boolean;
    "mixedPort": number;
    "profile": string;
    "profileName": string;

    /**
     * what is being done, e.g. "restarting"
     */
    "busy"?: string;
}
