// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status distinguishes an unreadable SSID from a confirmed disconnection.
 */
export interface Status {
    "ssid": string;

    /**
     * connected | disconnected | permission | denied | unavailable
     */
    "state": string;

    /**
     * the Wi-Fi interface, e.g. en0; "" without one
     */
    "interface": string;
}
