// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as backend$0 from "../../../../localhost-copilot/mihomobar/internal/backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as mihomoapi$0 from "../../../../localhost-copilot/mihomobar/internal/mihomoapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as profiles$0 from "../../../../localhost-copilot/mihomobar/internal/profiles/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "log": mihomoapi$0.Log;
            "memory": mihomoapi$0.Memory;
            "navigate": string;
            "profiles": profiles$0.Profile[] | null;
            "state": backend$0.State;
            "traffic": mihomoapi$0.Traffic;
        }
    }
}
