// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";

/**
 * AICheck combines a service's predicted routes with its nodes' exit addresses.
 */
export interface AICheck {
    "route": AIRoute;

    /**
     * The addresses are each node's, asked of Cloudflare through it rather
     * than of the service, which a node splitting by destination may not
     * show it.
     */
    "nodeEgress": boolean;

    /**
     * one per node the names leave by, the one most leave by first
     */
    "egress": AIEgress[] | null;

    /**
     * the worst finding: consistent (one node, or nodes sharing one
     * address), direct (every name leaves from this Mac), partlyDirect,
     * split, unsupported (an address in a region the service doesn't
     * serve), refused or failed
     */
    "status": string;

    /**
     * good | warn | bad | muted
     */
    "level": string;
}

/**
 * AIEgress is a node's Cloudflare-observed address and this service's route.
 */
export interface AIEgress {
    "node": string;

    /**
     * how many of the service's names leave by Node
     */
    "names": number;
    "ip": string;
    "loc": string;
    "chain": string[] | null;

    /**
     * the service doesn't serve Loc
     */
    "unsupported": boolean;

    /**
     * optional IPLocate metadata
     */
    "details": AIIPDetails | null;
    "error"?: string;
}

/**
 * AIHost is where the rules send one of a service's names.
 */
export interface AIHost {
    "host": string;
    "rule": string;
    "rulePayload": string;

    /**
     * node first; ["REJECT"] when refused
     */
    "chain": string[] | null;
    "error"?: string;
}

/**
 * AIIPDetails describes the observed IP using IPLocate's database.
 * Network is its containing ASN route, when supplied by the provider.
 */
export interface AIIPDetails {
    "city": string;
    "region": string;
    "operator": string;
    "asn": number;

    /**
     * ISP | Datacenter | Business | Unknown
     */
    "kind": string;
    "network": string;
}

/**
 * AIRoute is how a service's names leave.
 */
export interface AIRoute {
    "service": string;
    "hosts": AIHost[] | null;

    /**
     * the node most names leave by, the first name's on a tie
     */
    "node": string;

    /**
     * consistent: all leave by Node; split: by several nodes; direct:
     * some leave from this Mac; refused: all are refused; failed: none
     * could be routed
     */
    "verdict": string;

    /**
     * groups on the way that pick a node themselves (url-test, fallback,
     * load-balance), so the route may change later
     */
    "auto": string[] | null;
}

/**
 * AppUpdate is where updating the app stands, for Settings and the tray.
 */
export interface AppUpdate {
    /**
     * idle | checking | latest | downloading | ready | installed | available | source | error
     */
    "state": string;
    "latest"?: string;
    "notes"?: string;

    /**
     * the release page
     */
    "url"?: string;

    /**
     * available: why it can't replace itself
     */
    "stuck"?: string;
    "error"?: string;

    /**
     * downloading: bytes so far, of total (0 when unknown)
     */
    "done"?: number;
    "total"?: number;

    /**
     * unix ms of the last answer
     */
    "checked"?: number;
}

/**
 * CityGeoInfo is the city database's state, for Settings.
 */
export interface CityGeoInfo {
    "on": boolean;
    "ready": boolean;
    "downloading": boolean;
    "got": number;
    "of": number;

    /**
     * on disk
     */
    "size": number;

    /**
     * unix ms; 0 when there is none
     */
    "updated": number;
    "error": string;
}

/**
 * ClientRate is one app's traffic now, as Surge's "Top Clients" lists it:
 * its name, the path its icon comes from, and its speed in bytes a second.
 */
export interface ClientRate {
    "name": string;

    /**
     * the app bundle, or the executable; "" for a LAN client
     */
    "path": string;
    "up": number;
    "down": number;
}

/**
 * Connectivity is the four latencies Surge's overview shows (docs/design.md
 * §10.4): the router, DNS, the internet directly, and through the proxy.
 * Each is in ms; 0 means not measured, -1 failed. The router and DNS,
 * timed here, keep hundredths under 1 ms.
 */
export interface Connectivity {
    "router": number;
    "dns": number;
    "internet": number;
    "proxy": number;
    "gateway": string;

    /**
     * the policy the mode and rules sent the proxy test to
     */
    "via": string;

    /**
     * from the node out to Via
     */
    "chain": string[] | null;

    /**
     * "mihomo", or "system" when the profile has no dns section
     */
    "dnsVia": string;

    /**
     * the core's enhanced-mode: fake-ip | redir-host
     */
    "dnsMode": string;
}

/**
 * DNSEgress is where name lookups leave: the resolver that answers them
 * and the address authoritative servers see the queries come from, which
 * is the resolver's (or the proxy's), not this Mac's.
 */
export interface DNSEgress {
    /**
     * "mihomo", or "system" when the profile has no dns section
     */
    "via": string;

    /**
     * fake-ip | redir-host; "" for the system resolver
     */
    "mode": string;

    /**
     * the profile's nameservers, as written
     */
    "servers": string[] | null;

    /**
     * the egress address; "" when unknown
     */
    "ip": string;

    /**
     * the country of IP
     */
    "loc": string;

    /**
     * the client subnet passed upstream, if any
     */
    "ecs": string;
}

/**
 * Egress is where direct traffic leaves this Mac: the physical interface
 * and the public address sites see. Upstream of this Mac (a router running
 * a proxy, say) traffic may still be split by destination, so it is asked
 * of two: a mainland site, which sees the broadband line, and Cloudflare,
 * which sees where overseas traffic comes out. They differ when something
 * upstream proxies.
 */
export interface Egress {
    /**
     * e.g. en0
     */
    "interface": string;

    /**
     * its network service, e.g. Wi-Fi
     */
    "service": string;

    /**
     * as a mainland site sees it; "" when unknown
     */
    "domesticIp": string;

    /**
     * the country of DomesticIP
     */
    "domesticLoc": string;

    /**
     * as Cloudflare sees it; "" when unknown
     */
    "ip": string;

    /**
     * the country of IP
     */
    "loc": string;
}

/**
 * Event is something that happened, for the events list and, when Notify
 * is set, a notification. Text is English, with {name}s filled from Args,
 * so each page can translate it.
 */
export interface Event {
    "id": number;
    "time": string;

    /**
     * core | proxy | network | profile | group
     */
    "kind": string;

    /**
     * info | warning | error
     */
    "level": string;
    "text": string;
    "args"?: { [_ in string]?: string } | null;
    "notify": boolean;
}

/**
 * GeoInfo is the core's GEO databases: when they last changed (unix ms, 0
 * when there are none yet) and whether an update is under way.
 */
export interface GeoInfo {
    "updated": number;
    "updating": boolean;
}

/**
 * Globe is where the connections go now, for the overview's globe: from
 * this Mac, through the countries the nodes' names give, to the
 * destination. Places are countries' centres, or with the city database
 * the cities the addresses are in.
 */
export interface Globe {
    /**
     * this Mac's place; "" while unknown
     */
    "origin": string;

    /**
     * the public address it was found from
     */
    "originIp": string;

    /**
     * every place named here
     */
    "places": { [_ in string]?: Place } | null;

    /**
     * the busiest first
     */
    "routes": GlobeRoute[] | null;

    /**
     * places come from the city database
     */
    "cities": boolean;
}

/**
 * GlobeEnd is a route's connections to one place.
 */
export interface GlobeEnd {
    "at": string;
    "conns": number;
    "up": number;
    "down": number;
    "total": number;
    "hosts": GlobeHost[] | null;
}

export interface GlobeHost {
    "host": string;
    "total": number;
}

/**
 * GlobeRoute is the connections to one country by one way: directly, or
 * through nodes in the countries of Via.
 */
export interface GlobeRoute {
    /**
     * the country
     */
    "to": string;

    /**
     * the nodes' countries, in the order the data goes: front nodes first, the exit last; none for DIRECT, or nodes whose names don't say
     */
    "via": string[] | null;
    "direct": boolean;
    "conns": number;

    /**
     * bytes a second
     */
    "up": number;
    "down": number;

    /**
     * what its connections have moved
     */
    "total": number;

    /**
     * the busiest, at most globeHosts
     */
    "hosts": GlobeHost[] | null;

    /**
     * the places in To it reaches, the busiest first
     */
    "ends": GlobeEnd[] | null;
}

/**
 * HelperStatus is what Settings shows of service mode.
 */
export interface HelperStatus {
    "installed": boolean;

    /**
     * runs this version of the app
     */
    "current": boolean;

    /**
     * settings.ServiceMode
     */
    "enabled": boolean;

    /**
     * the running core is the helper's
     */
    "active": boolean;
}

/**
 * LatencyEvent describes one test operation. Pending contains display names,
 * including group aliases; Delays contains only the newly completed results.
 */
export interface LatencyEvent {
    "key": string;
    "running": boolean;
    "pending": string[] | null;
    "delays": { [_ in string]?: number } | null;
    "total": number;
    "completed": number;
    "failed": number;
}

export interface LatencyResult {
    "total": number;
    "failed": number;
}

/**
 * LatencySample is one measure of a connectivity item, for the bars under
 * its card.
 */
export interface LatencySample {
    "key": string;

    /**
     * unix ms
     */
    "at": number;

    /**
     * -1 failed
     */
    "ms": number;

    /**
     * the first after the network changed
     */
    "break"?: boolean;
}

/**
 * Line is a line of the merged configuration shown against the profile:
 * Op is "+" for a line the profile doesn't have, "-" for one of the
 * profile's that is gone, "" for one kept, and Source what added or
 * removed it (runtimecfg.Layer's, or "stale" for a difference between the
 * configuration the core has and what the settings make now).
 */
export interface Line {
    "text": string;
    "op"?: string;
    "source"?: string;
}

/**
 * Lookup is what the core makes of a name: how its resolver answers, and
 * the rule and route a connection to it takes.
 */
export interface Lookup {
    "host": string;
    "port": number;

    /**
     * the profile's enhanced-mode; "" with DNS off
     */
    "dnsMode": string;

    /**
     * mihomo, or system when the profile has no DNS
     */
    "dnsVia": string;
    "a": Record[] | null;
    "aaaa": Record[] | null;
    "cname": string[] | null;
    "dnsError"?: string;

    /**
     * how a connection to host:port is routed
     */
    "rule": string;
    "rulePayload": string;

    /**
     * node first, as the core has it
     */
    "chain": string[] | null;
    "remoteIp": string;

    /**
     * RemoteIP is in the fake-ip range: another fake-ip resolver (a TUN
     * upstream, say) answered for the system
     */
    "remoteFake": boolean;
    "routeError"?: string;
}

/**
 * Network is the network the Mac is on and what the rules make of it
 * (docs/design.md §10.3.3).
 */
export interface Network {
    "wifi": wifi$0.Status;

    /**
     * wifi | wired | "" offline
     */
    "kind": string;

    /**
     * the rule in effect, as ruleKey names it; "" offline or not settled
     */
    "match": string;

    /**
     * the fields the rule sets that were changed by hand since: profile,
     * mode, systemProxy, tun, group:<name>
     */
    "manual": string[] | null;
    "expensive": boolean;
    "constrained": boolean;

    /**
     * SaveData is on and the network is expensive or constrained
     */
    "savingData": boolean;
}

/**
 * Node is one of the running profile's nodes, for a route to pick from.
 */
export interface Node {
    "name": string;
    "type": string;

    /**
     * last test, ms; 0 untested, -1 failed
     */
    "delay": number;

    /**
     * the first modules.Regions key that takes it
     */
    "region"?: string;
}

/**
 * Place is a country ("JP") or a city in one ("JP/Osaka").
 */
export interface Place {
    "lat": number;
    "lon": number;
    "cc": string;
    "city"?: string;
}

/**
 * PortState is how a port module's port came up in the running core. The
 * core only logs a listener it can't open and goes on, so it is asked which
 * ports it really holds (/clashcube/listening).
 */
export interface PortState {
    "port": number;

    /**
     * "open", "taken" (by another program) or "closed"
     */
    "status": string;

    /**
     * the program holding a taken port, when known
     */
    "holder"?: string;
}

/**
 * ProxyEgress is where proxied traffic leaves: the address Cloudflare sees
 * a request through the core come from, and the chain it took.
 */
export interface ProxyEgress {
    "ip": string;
    "loc": string;

    /**
     * from the node out to the policy
     */
    "chain": string[] | null;
}

/**
 * Record is an address the resolver gave. Under fake-ip, apps are handed
 * an address from the pool instead; these are the real ones the core
 * connects to.
 */
export interface Record {
    "data": string;
    "ttl": number;
}

/**
 * Refusal is the last configuration the core, or the merge before it,
 * refused: the error, and the line of Source it points to (0 when it
 * names none). Source is "runtime" for the merged configuration and
 * "profile" for the profile in use, which was not YAML.
 */
export interface Refusal {
    "error": string;
    "line": number;
    "source": string;
}

/**
 * RegionNodes is a region and how many of the running profile's nodes it
 * takes; Count is -1 with the core stopped.
 */
export interface RegionNodes {
    "key": string;

    /**
     * English, translated on the page
     */
    "name": string;
    "count": number;
}

/**
 * RuleEntries is what a rule set, GeoSite list or GeoIP list holds, read
 * from the files the core uses. Entries are those matching the query, at
 * most the limit asked for.
 */
export interface RuleEntries {
    /**
     * the file, relative to the core's home; "inline" for one in the profile
     */
    "source": string;

    /**
     * domain | ipcidr | classical, for rule sets
     */
    "behavior": string;
    "total": number;
    "matched": number;
    "entries": string[] | null;

    /**
     * Note is why there is nothing to list: not fetched yet, or a database
     * that can't be listed. English, translated by the window.
     */
    "note"?: string;

    /**
     * Not means the rule matches everything except these (GEOSITE,!cn).
     */
    "not"?: boolean;
}

/**
 * RuntimeView is the configuration the core was last given, and the last
 * one refused since, as written, the controller's secret too. Lines is
 * Body against the profile it was made from, when the profile can be read.
 */
export interface RuntimeView {
    "body": string;
    "lines"?: Line[] | null;
    "refusal"?: Refusal | null;
    "refused"?: string;
}

/**
 * State is what the GUI shows of the app at a glance.
 */
export interface State {
    /**
     * coremgr.Status
     */
    "core": string;
    "coreError"?: string;
    "coreVersion": string;
    "appVersion": string;
    "mode": string;
    "systemProxy": boolean;

    /**
     * another app took the system proxy over; ours is no longer in effect
     */
    "proxyLost": boolean;
    "tun": boolean;
    "tunStack": string;
    "serviceMode": boolean;
    "mixedPort": number;
    "profile": string;
    "profileName": string;

    /**
     * what is being done, e.g. "restarting"
     */
    "busy"?: string;
    "network": Network;

    /**
     * the last configuration refused, until one is taken
     */
    "refusal"?: Refusal | null;

    /**
     * how the port modules' ports came up (portstate.go)
     */
    "ports": PortState[] | null;

    /**
     * updating the app itself (appupdate.go)
     */
    "update": AppUpdate;
}
