// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";

/**
 * ClientRate is one app's traffic now, as Surge's "Top Clients" lists it:
 * its name, the path its icon comes from, and its speed in bytes a second.
 */
export interface ClientRate {
    "name": string;

    /**
     * the app bundle, or the executable; "" for a LAN client
     */
    "path": string;
    "up": number;
    "down": number;
}

/**
 * Connectivity is the four latencies Surge's overview shows (docs/design.md
 * §10.4): the router, DNS, the internet directly, and through the proxy.
 * Each is in ms; 0 means not measured, -1 failed. The router and DNS,
 * timed here, keep hundredths under 1 ms.
 */
export interface Connectivity {
    "router": number;
    "dns": number;
    "internet": number;
    "proxy": number;
    "gateway": string;

    /**
     * the policy the mode and rules sent the proxy test to
     */
    "via": string;

    /**
     * from the node out to Via
     */
    "chain": string[] | null;

    /**
     * "mihomo", or "system" when the profile has no dns section
     */
    "dnsVia": string;

    /**
     * the core's enhanced-mode: fake-ip | redir-host
     */
    "dnsMode": string;
}

/**
 * DNSEgress is where name lookups leave: the resolver that answers them
 * and the address authoritative servers see the queries come from, which
 * is the resolver's (or the proxy's), not this Mac's.
 */
export interface DNSEgress {
    /**
     * "mihomo", or "system" when the profile has no dns section
     */
    "via": string;

    /**
     * fake-ip | redir-host; "" for the system resolver
     */
    "mode": string;

    /**
     * the profile's nameservers, as written
     */
    "servers": string[] | null;

    /**
     * the egress address; "" when unknown
     */
    "ip": string;

    /**
     * the country of IP
     */
    "loc": string;

    /**
     * the client subnet passed upstream, if any
     */
    "ecs": string;
}

/**
 * Egress is where direct traffic leaves this Mac: the physical interface
 * and the public address sites see. Upstream of this Mac (a router running
 * a proxy, say) traffic may still be split by destination, so it is asked
 * of two: a mainland site, which sees the broadband line, and Cloudflare,
 * which sees where overseas traffic comes out. They differ when something
 * upstream proxies.
 */
export interface Egress {
    /**
     * e.g. en0
     */
    "interface": string;

    /**
     * its network service, e.g. Wi-Fi
     */
    "service": string;

    /**
     * as a mainland site sees it; "" when unknown
     */
    "domesticIp": string;

    /**
     * the country of DomesticIP
     */
    "domesticLoc": string;

    /**
     * as Cloudflare sees it; "" when unknown
     */
    "ip": string;

    /**
     * the country of IP
     */
    "loc": string;
}

/**
 * Event is something that happened, for the events list and, when Notify
 * is set, a notification. Text is English, with {name}s filled from Args,
 * so each page can translate it.
 */
export interface Event {
    "id": number;
    "time": string;

    /**
     * core | proxy | network | profile | group
     */
    "kind": string;

    /**
     * info | warning | error
     */
    "level": string;
    "text": string;
    "args"?: { [_ in string]?: string } | null;
    "notify": boolean;
}

/**
 * GeoInfo is the core's GEO databases: when they last changed (unix ms, 0
 * when there are none yet) and whether an update is under way.
 */
export interface GeoInfo {
    "updated": number;
    "updating": boolean;
}

/**
 * HelperStatus is what Settings shows of service mode.
 */
export interface HelperStatus {
    "installed": boolean;

    /**
     * runs this version of the app
     */
    "current": boolean;

    /**
     * settings.ServiceMode
     */
    "enabled": boolean;

    /**
     * the running core is the helper's
     */
    "active": boolean;
}

/**
 * LatencyEvent describes one test operation. Pending contains display names,
 * including group aliases; Delays contains only the newly completed results.
 */
export interface LatencyEvent {
    "key": string;
    "running": boolean;
    "pending": string[] | null;
    "delays": { [_ in string]?: number } | null;
    "total": number;
    "completed": number;
    "failed": number;
}

export interface LatencyResult {
    "total": number;
    "failed": number;
}

/**
 * LatencySample is one measure of a connectivity item, for the bars under
 * its card.
 */
export interface LatencySample {
    "key": string;

    /**
     * unix ms
     */
    "at": number;

    /**
     * -1 failed
     */
    "ms": number;

    /**
     * the first after the network changed
     */
    "break"?: boolean;
}

/**
 * Lookup is what the core makes of a name: how its resolver answers, and
 * the rule and route a connection to it takes.
 */
export interface Lookup {
    "host": string;
    "port": number;

    /**
     * the profile's enhanced-mode; "" with DNS off
     */
    "dnsMode": string;

    /**
     * mihomo, or system when the profile has no DNS
     */
    "dnsVia": string;
    "a": Record[] | null;
    "aaaa": Record[] | null;
    "cname": string[] | null;
    "dnsError"?: string;

    /**
     * how a connection to host:port is routed
     */
    "rule": string;
    "rulePayload": string;

    /**
     * node first, as the core has it
     */
    "chain": string[] | null;
    "remoteIp": string;

    /**
     * RemoteIP is in the fake-ip range: another fake-ip resolver (a TUN
     * upstream, say) answered for the system
     */
    "remoteFake": boolean;
    "routeError"?: string;
}

/**
 * Network is the network the Mac is on and what the rules make of it
 * (docs/design.md §10.3.3).
 */
export interface Network {
    "wifi": wifi$0.Status;

    /**
     * wifi | wired | "" offline
     */
    "kind": string;

    /**
     * the rule in effect, as ruleKey names it; "" offline or not settled
     */
    "match": string;

    /**
     * the fields the rule sets that were changed by hand since: profile,
     * mode, systemProxy, tun, group:<name>
     */
    "manual": string[] | null;
    "expensive": boolean;
    "constrained": boolean;

    /**
     * SaveData is on and the network is expensive or constrained
     */
    "savingData": boolean;
}

/**
 * Node is one of the running profile's nodes, for a route to pick from.
 */
export interface Node {
    "name": string;
    "type": string;

    /**
     * last test, ms; 0 untested, -1 failed
     */
    "delay": number;

    /**
     * the first modules.Regions key that takes it
     */
    "region"?: string;
}

/**
 * ProxyEgress is where proxied traffic leaves: the address Cloudflare sees
 * a request through the core come from, and the chain it took.
 */
export interface ProxyEgress {
    "ip": string;
    "loc": string;

    /**
     * from the node out to the policy
     */
    "chain": string[] | null;
}

/**
 * Record is an address the resolver gave. Under fake-ip, apps are handed
 * an address from the pool instead; these are the real ones the core
 * connects to.
 */
export interface Record {
    "data": string;
    "ttl": number;
}

/**
 * RegionNodes is a region and how many of the running profile's nodes it
 * takes; Count is -1 with the core stopped.
 */
export interface RegionNodes {
    "key": string;

    /**
     * English, translated on the page
     */
    "name": string;
    "count": number;
}

/**
 * RuleEntries is what a rule set, GeoSite list or GeoIP list holds, read
 * from the files the core uses. Entries are those matching the query, at
 * most the limit asked for.
 */
export interface RuleEntries {
    /**
     * the file, relative to the core's home; "inline" for one in the profile
     */
    "source": string;

    /**
     * domain | ipcidr | classical, for rule sets
     */
    "behavior": string;
    "total": number;
    "matched": number;
    "entries": string[] | null;

    /**
     * Note is why there is nothing to list: not fetched yet, or a database
     * that can't be listed. English, translated by the window.
     */
    "note"?: string;

    /**
     * Not means the rule matches everything except these (GEOSITE,!cn).
     */
    "not"?: boolean;
}

/**
 * State is what the GUI shows of the app at a glance.
 */
export interface State {
    /**
     * coremgr.Status
     */
    "core": string;
    "coreError"?: string;
    "coreVersion": string;
    "appVersion": string;
    "mode": string;
    "systemProxy": boolean;

    /**
     * another app took the system proxy over; ours is no longer in effect
     */
    "proxyLost": boolean;
    "tun": boolean;
    "tunStack": string;
    "serviceMode": boolean;
    "mixedPort": number;
    "profile": string;
    "profileName": string;

    /**
     * what is being done, e.g. "restarting"
     */
    "busy"?: string;
    "network": Network;
}
