// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Connection {
    "id": string;
    "metadata": Metadata;
    "upload": number;
    "download": number;
    "start": string;
    "chains": string[] | null;
    "rule": string;
    "rulePayload": string;
}

export interface Connections {
    "downloadTotal": number;
    "uploadTotal": number;
    "connections": Connection[] | null;
    "memory": number;
}

export interface Log {
    "type": string;
    "payload": string;
}

export interface Memory {
    "inuse": number;
    "oslimit": number;
}

export interface Metadata {
    "network": string;
    "type": string;
    "sourceIP": string;
    "destinationIP": string;
    "sourcePort": string;
    "destinationPort": string;
    "host": string;
    "sniffHost": string;
    "process": string;
    "processPath": string;
    "remoteDestination": string;
}

export interface Rule {
    "index": number;
    "type": string;
    "payload": string;
    "proxy": string;
    "size": number;
}

export interface Traffic {
    "up": number;
    "down": number;
    "upTotal": number;
    "downTotal": number;
}
