// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Profile {
    "id": string;
    "name": string;

    /**
     * empty for a local file
     */
    "url"?: string;

    /**
     * auto update, in hours; 0 never
     */
    "interval": number;
    "updated": string;

    /**
     * From the subscription-userinfo header, in bytes and Unix seconds.
     */
    "upload"?: number;
    "download"?: number;
    "total"?: number;
    "expire"?: number;
}
