// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportRequest pre-fills the import form. Parsing never downloads or activates
 * a profile; an external link still needs the user's confirmation in the app.
 */
export interface ImportRequest {
    "url": string;
    "name": string;
    "error"?: string;
}

export interface Profile {
    "id": string;
    "name": string;

    /**
     * empty for a local file
     */
    "url"?: string;

    /**
     * auto update, in hours; 0 never
     */
    "interval": number;
    "updated": string;

    /**
     * From the subscription-userinfo header, in bytes and Unix seconds.
     */
    "upload"?: number;
    "download"?: number;
    "total"?: number;
    "expire"?: number;
}
