// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bar is one hour of a day, or one day of a range.
 */
export interface Bar {
    /**
     * the hour ("0"–"23") or the date
     */
    "key": string;
    "up": number;
    "down": number;
}

/**
 * Report is the traffic of the days from..to (dates, inclusive), or of
 * one hour of a single day.
 */
export interface Report {
    "from": string;
    "to": string;

    /**
     * -1: the whole period
     */
    "hour": number;
    "up": number;
    "down": number;
    "conns": number;
    "bars": Bar[] | null;
    "dims": { [_ in string]?: Row[] | null } | null;
}

/**
 * Row is an entry over the report's period.
 */
export interface Row {
    "key": string;
    "name": string;
    "path"?: string;
    "up": number;
    "down": number;
    "conns": number;
}
