// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the app and its windows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "../usage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AICheck is where the rules send each of an AI service's names ("OpenAI"
 * or "Claude") and the address the service sees through each node they
 * leave by; force bypasses the local IP attribute cache.
 */
export function AICheck(service: string, force: boolean): $CancellablePromise<backend$0.AICheck> {
    return $Call.ByID(4110234925, service, force);
}

/**
 * AppIcon is an app's icon (a bundle or executable path; "" for a LAN
 * client) as a PNG data URL, for the page to show.
 */
export function AppIcon(path: string): $CancellablePromise<string> {
    return $Call.ByID(1938876913, path);
}

/**
 * ChooseApp asks for an app or an executable; a cancelled dialog is the
 * zero App.
 */
export function ChooseApp(): $CancellablePromise<$models.App> {
    return $Call.ByID(1465706359);
}

export function ClearEvents(): $CancellablePromise<void> {
    return $Call.ByID(1896544371);
}

/**
 * ClearUsage forgets the traffic statistics.
 */
export function ClearUsage(): $CancellablePromise<void> {
    return $Call.ByID(3489719313);
}

/**
 * Connectivity measures router, DNS, internet and proxy latency.
 */
export function Connectivity(): $CancellablePromise<backend$0.Connectivity> {
    return $Call.ByID(892611526);
}

/**
 * ConnectivityHistory is each item's recent measures, oldest first.
 */
export function ConnectivityHistory(): $CancellablePromise<{ [_ in string]?: backend$0.LatencySample[] | null } | null> {
    return $Call.ByID(52999182);
}

/**
 * ConnectivityItem measures one of "router", "dns", "internet", "proxy";
 * only that item's fields are set.
 */
export function ConnectivityItem(key: string): $CancellablePromise<backend$0.Connectivity> {
    return $Call.ByID(2264389125, key);
}

export function CopyText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1697171583, text);
}

/**
 * DNSEgress is the resolver in use and the address its queries leave from.
 */
export function DNSEgress(): $CancellablePromise<backend$0.DNSEgress> {
    return $Call.ByID(1670315567);
}

/**
 * DirectEgress is the direct route's interface and public address.
 */
export function DirectEgress(): $CancellablePromise<backend$0.Egress> {
    return $Call.ByID(1011092207);
}

/**
 * DisableServiceMode runs the core as the user again; uninstall removes the helper.
 */
export function DisableServiceMode(uninstall: boolean): $CancellablePromise<void> {
    return $Call.ByID(772624569, uninstall);
}

/**
 * EnableServiceMode installs the privileged helper (asking for a password).
 */
export function EnableServiceMode(): $CancellablePromise<void> {
    return $Call.ByID(4090658782);
}

/**
 * Events is the recent events, oldest first.
 */
export function Events(): $CancellablePromise<backend$0.Event[] | null> {
    return $Call.ByID(1021534600);
}

/**
 * FitPanel sizes the tray panel to its page's height (CSS pixels), gliding
 * over ms when it is shown.
 */
export function FitPanel(height: number, ms: number): $CancellablePromise<void> {
    return $Call.ByID(4075873230, height, ms);
}

/**
 * HelperStatus is service mode's state, for Settings.
 */
export function HelperStatus(): $CancellablePromise<backend$0.HelperStatus> {
    return $Call.ByID(326769315);
}

export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(2568592905);
}

/**
 * LANProxyCommand is the same for this Mac's LAN address, for another
 * machine to use (Allow LAN must be on); "" when the Mac has none.
 */
export function LANProxyCommand(): $CancellablePromise<string> {
    return $Call.ByID(3327025741);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3602974294, url);
}

/**
 * ProxyCommand is the shell export line for the mixed port.
 */
export function ProxyCommand(): $CancellablePromise<string> {
    return $Call.ByID(2722061236);
}

/**
 * ProxyEgress is where proxied traffic leaves, and the chain it took.
 */
export function ProxyEgress(): $CancellablePromise<backend$0.ProxyEgress> {
    return $Call.ByID(855216144);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(1311964722);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(100359480);
}

export function RevealData(): $CancellablePromise<void> {
    return $Call.ByID(3291061748);
}

/**
 * RevealData opens the app's data folder in Finder.
 * RunningApps is the apps running now, for a process rule to name.
 */
export function RunningApps(): $CancellablePromise<$models.App[] | null> {
    return $Call.ByID(2333957600);
}

export function SetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(2527848048, mode);
}

export function SetSystemProxy(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(763356946, on);
}

export function SetTun(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(2618200030, on);
}

/**
 * ShowMain opens the main window, on view if one is given.
 */
export function ShowMain(view: string): $CancellablePromise<void> {
    return $Call.ByID(2391679925, view);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(184712387);
}

export function State(): $CancellablePromise<backend$0.State> {
    return $Call.ByID(502501410);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3279807313);
}

/**
 * Usage is the traffic statistics of the days from..to ("2006-01-02",
 * inclusive); a single day comes in hours, and hour (0–23, else -1)
 * narrows it to one.
 */
export function Usage($from: string, to: string, hour: number): $CancellablePromise<usage$0.Report> {
    return $Call.ByID(3971713940, $from, to, hour);
}
