// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is a program a process rule can name.
 */
export interface App {
    "name": string;

    /**
     * its .app, "" for a bare executable
     */
    "bundle": string;

    /**
     * the binary
     */
    "executable": string;
}

/**
 * Group is a proxy group with its members, in the profile's order.
 */
export interface Group {
    "name": string;
    "type": string;
    "now": string;
    "hidden": boolean;
    "icon": string;
    "testUrl": string;
    "members": Member[] | null;

    /**
     * the ID of the module that made it
     */
    "module"?: string;
}

/**
 * Hotkey is an action's global shortcut, as Settings shows it.
 */
export interface Hotkey {
    "action": string;

    /**
     * as "Ctrl+Option+Cmd+P"; "" for none
     */
    "keys": string;

    /**
     * why it isn't working
     */
    "error"?: string;
}

export interface Member {
    "name": string;
    "type": string;
    "udp": boolean;

    /**
     * last test, ms; 0 untested, -1 failed
     */
    "delay": number;

    /**
     * a group itself
     */
    "group": boolean;
}

/**
 * Patch is a partial update: the keys of p (as settings.json names them)
 * that are present are changed.
 */
export interface Patch {
    "mixedPort"?: number | null;
    "allowLan"?: boolean | null;
    "ipv6"?: boolean | null;
    "logLevel"?: string | null;
    "tunStack"?: string | null;
    "icmpForwarding"?: boolean | null;
    "guardIPv6"?: boolean | null;
    "guardDNS"?: boolean | null;
    "blockSTUN"?: boolean | null;
    "dnsRespectRules"?: boolean | null;
    "unifiedDelay"?: boolean | null;
    "bypass"?: string[] | null;
    "autoStart"?: boolean | null;
    "launchAtLogin"?: boolean | null;
    "theme"?: string | null;
    "lang"?: string | null;
    "dock"?: string | null;
    "testUrl"?: string | null;
    "traySpeed"?: boolean | null;
    "findProcess"?: boolean | null;
    "notify"?: boolean | null;
    "saveData"?: boolean | null;
    "aiServices"?: string[] | null;
}

/**
 * Provider is a proxy provider with its nodes, as the profile lists them.
 */
export interface Provider {
    "name": string;

    /**
     * HTTP | File | Inline
     */
    "vehicleType": string;
    "testUrl": string;
    "updatedAt": string;
    "upload": number;
    "download": number;
    "total": number;
    "expire": number;
    "members": Member[] | null;
}

/**
 * Recommended is what UseRecommendedHotkeys did: the shortcuts now, and
 * the actions it left without one, the shortcut being taken.
 */
export interface Recommended {
    "hotkeys": Hotkey[] | null;
    "skipped": string[] | null;
}
