// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService is the core's proxies, groups, connections and rules.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mihomoapi$0 from "../mihomoapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as userrules$0 from "../userrules/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTempRule puts a temporary rule first.
 */
export function AddTempRule(r: userrules$0.Rule): $CancellablePromise<void> {
    return $Call.ByID(555889169, r);
}

/**
 * AddUserRule puts a rule first.
 */
export function AddUserRule(r: userrules$0.Rule): $CancellablePromise<void> {
    return $Call.ByID(2013020188, r);
}

/**
 * CityGeoInfo is the globe's city database: whether it is on, there, or
 * being downloaded.
 */
export function CityGeoInfo(): $CancellablePromise<backend$0.CityGeoInfo> {
    return $Call.ByID(668103062);
}

export function CloseAllConnections(): $CancellablePromise<void> {
    return $Call.ByID(3536186298);
}

export function CloseConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1048077390, id);
}

export function Connections(): $CancellablePromise<mihomoapi$0.Connections> {
    return $Call.ByID(3835731179);
}

export function FlushDNS(): $CancellablePromise<void> {
    return $Call.ByID(116756319);
}

/**
 * GeoInfo is when the GEO databases last changed, and whether an update runs.
 */
export function GeoInfo(): $CancellablePromise<backend$0.GeoInfo> {
    return $Call.ByID(2455580795);
}

/**
 * Globe is the connections by the country they go to, and the way they
 * take there, with speeds since the last call.
 */
export function Globe(): $CancellablePromise<backend$0.Globe> {
    return $Call.ByID(1821532211);
}

/**
 * Groups is every proxy group, GLOBAL last.
 */
export function Groups(): $CancellablePromise<$models.Group[] | null> {
    return $Call.ByID(576014054);
}

/**
 * LookupHost tells how the core resolves and routes host (a name, an
 * address, host:port or a URL).
 */
export function LookupHost(host: string): $CancellablePromise<backend$0.Lookup> {
    return $Call.ByID(3488974690, host);
}

/**
 * Providers is the profile's proxy providers, by name; the ones the core
 * makes for groups' own proxies are left out.
 */
export function Providers(): $CancellablePromise<$models.Provider[] | null> {
    return $Call.ByID(2883209048);
}

/**
 * RuleEntries lists what a rule set (kind ruleset), GeoSite or GeoIP list
 * holds: the entries containing query, at most limit of them.
 */
export function RuleEntries(kind: string, name: string, query: string, limit: number): $CancellablePromise<backend$0.RuleEntries> {
    return $Call.ByID(2414992664, kind, name, query, limit);
}

/**
 * RuleProviders is the profile's rule providers, by name.
 */
export function RuleProviders(): $CancellablePromise<mihomoapi$0.RuleProvider[] | null> {
    return $Call.ByID(3435162274);
}

/**
 * RuleTypes is the rule types a user rule can have.
 */
export function RuleTypes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2583247177);
}

export function Rules(): $CancellablePromise<mihomoapi$0.Rule[] | null> {
    return $Call.ByID(84247521);
}

/**
 * Select picks a group's member; the old one's connections are closed so
 * the switch shows at once.
 */
export function Select(group: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2748071622, group, name);
}

/**
 * SetCityGeo turns the city database on, downloading it, or off, removing it.
 */
export function SetCityGeo(on: boolean): $CancellablePromise<backend$0.CityGeoInfo> {
    return $Call.ByID(3276503246, on);
}

/**
 * SetTempRules replaces them; the core takes them at once.
 */
export function SetTempRules(rs: userrules$0.Rule[] | null): $CancellablePromise<void> {
    return $Call.ByID(3183893147, rs);
}

/**
 * SetUserRules replaces them; the core takes them at once.
 */
export function SetUserRules(rs: userrules$0.Rule[] | null): $CancellablePromise<void> {
    return $Call.ByID(3372887460, rs);
}

/**
 * TempRules is the rules added for now only, ahead of the saved ones; a
 * profile switch or update drops them.
 */
export function TempRules(): $CancellablePromise<userrules$0.Rule[] | null> {
    return $Call.ByID(2753390755);
}

/**
 * TestLatency shares scheduling, progress and results across all surfaces.
 */
export function TestLatency(kind: string, name: string): $CancellablePromise<backend$0.LatencyResult> {
    return $Call.ByID(2059967740, kind, name);
}

/**
 * TopClients is the n apps moving the most traffic, their speeds measured
 * since the last call. After a pause (the panel was hidden) it starts over,
 * and the first call has no speeds yet.
 */
export function TopClients(n: number): $CancellablePromise<backend$0.ClientRate[] | null> {
    return $Call.ByID(3577893539, n);
}

/**
 * UpdateCityGeo downloads the city database again.
 */
export function UpdateCityGeo(): $CancellablePromise<backend$0.CityGeoInfo> {
    return $Call.ByID(2119358229);
}

/**
 * UpdateGeo waits for the core to download its GEO databases; Updating in
 * the result means one was already under way.
 */
export function UpdateGeo(): $CancellablePromise<backend$0.GeoInfo> {
    return $Call.ByID(882741232);
}

/**
 * UpdateProvider fetches a proxy provider again.
 */
export function UpdateProvider(name: string): $CancellablePromise<void> {
    return $Call.ByID(3984343286, name);
}

/**
 * UpdateRuleProvider fetches a rule provider again; the core keeps the
 * rules it had when the fetch fails.
 */
export function UpdateRuleProvider(name: string): $CancellablePromise<void> {
    return $Call.ByID(3888899584, name);
}

/**
 * UserRules is the rules added in the app, ahead of the profile's.
 */
export function UserRules(): $CancellablePromise<userrules$0.Rule[] | null> {
    return $Call.ByID(273927228);
}
