// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Rule is one rule, as mihomo writes it: TYPE,payload,policy.
 */
export interface Rule {
    "type": string;
    "payload": string;
    "policy": string;
}
