// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Settings {
    /**
     * Profile is the id of the profile in use.
     */
    "profile": string;

    /**
     * What the app lays over every profile (runtimecfg).
     * rule | global | direct
     */
    "mode": string;
    "mixedPort": number;
    "allowLan": boolean;
    "ipv6": boolean;
    "logLevel": string;

    /**
     * system | gvisor | mixed
     */
    "tunStack": string;
    "systemProxy": boolean;
    "tun": boolean;
    "bypass": string[] | null;

    /**
     * The core runs through the root helper (service mode) once TUN has been
     * turned on; it stays there until the helper is removed.
     */
    "serviceMode": boolean;

    /**
     * start the core when the app opens
     */
    "autoStart": boolean;
    "launchAtLogin": boolean;

    /**
     * system | light | dark
     */
    "theme": string;

    /**
     * system | en | zh
     */
    "lang": string;

    /**
     * never | always | window
     */
    "dock": string;
    "testUrl": string;

    /**
     * speed beside the menu bar icon
     */
    "traySpeed": boolean;
    "window"?: number[] | null;
}
