// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface NetworkActions {
    "profile"?: string;

    /**
     * rule | global | direct
     */
    "mode"?: string;
    "systemProxy"?: boolean | null;
    "tun"?: boolean | null;

    /**
     * selector group → member
     */
    "groups"?: { [_ in string]?: string } | null;
}

/**
 * NetworkRule is what to set while on the networks it matches: a Wi-Fi
 * network by its exact, case-sensitive SSID, any wired network, or, for the
 * one "other" rule, every other network. Unset actions leave things be.
 */
export interface NetworkRule {
    /**
     * ssid | wired | other
     */
    "match": string;
    "ssid"?: string;
    "actions": NetworkActions;
}

export interface Settings {
    /**
     * Profile is the id of the profile in use.
     */
    "profile": string;

    /**
     * What the app lays over every profile (runtimecfg).
     * rule | global | direct
     */
    "mode": string;
    "mixedPort": number;
    "allowLan": boolean;
    "ipv6": boolean;
    "logLevel": string;

    /**
     * system | gvisor | mixed
     */
    "tunStack": string;

    /**
     * ICMPForwarding sends pings under TUN out directly; off, the core
     * answers them itself. ICMP is never proxied either way.
     */
    "icmpForwarding": boolean;

    /**
     * Leak protection (runtimecfg). GuardIPv6 routes IPv6 into the TUN
     * even with IPv6 off; GuardDNS makes the core answer every lookup;
     * BlockSTUN rejects STUN over UDP, which WebRTC would send direct when
     * a node has no UDP; DNSRespectRules sends the core's own lookups the
     * way the rules send their domains.
     */
    "guardIPv6": boolean;
    "guardDNS": boolean;
    "blockSTUN": boolean;
    "dnsRespectRules": boolean;
    "systemProxy": boolean;
    "tun": boolean;
    "bypass": string[] | null;

    /**
     * The core runs through the root helper (service mode) once TUN has been
     * turned on; it stays there until the helper is removed.
     */
    "serviceMode": boolean;

    /**
     * start the core when the app opens
     */
    "autoStart": boolean;
    "launchAtLogin": boolean;

    /**
     * system | light | dark
     */
    "theme": string;

    /**
     * system | en | zh
     */
    "lang": string;

    /**
     * never | always | window
     */
    "dock": string;
    "testUrl": string;

    /**
     * look up the process of every connection
     */
    "findProcess": boolean;

    /**
     * speed beside the menu bar icon
     */
    "traySpeed": boolean;

    /**
     * notifications for the events that ask for one
     */
    "notify": boolean;
    "window"?: number[] | null;

    /**
     * NetworkAuto applies NetworkRules as the Mac moves between networks.
     */
    "networkAuto": boolean;
    "networkRules": NetworkRule[] | null;

    /**
     * SaveData pauses the app's own background traffic on networks macOS
     * marks expensive (a personal hotspot) or constrained (Low Data Mode).
     */
    "saveData": boolean;
}
