// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Module {
    "id": string;
    "name": string;
    "enabled": boolean;

    /**
     * YAML, a mapping
     */
    "body": string;
}
