// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Module {
    "id": string;
    "name": string;
    "enabled": boolean;

    /**
     * YAML, a mapping
     */
    "body": string;
}

/**
 * Template is a module offered ready-made, for the cases most people add
 * one for. Hint says in a line what it does and when to want it; a Draft
 * holds an example to replace, so it opens in the editor rather than being
 * added as it is.
 */
export interface Template {
    "name": string;
    "hint": string;
    "body": string;
    "draft"?: boolean;
}
